### ISSUE TITLE
make distclean fails

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/nq#10]
On debian buster I do 

$ ./configure --with-gaproot=/usr/share/gap

followed by 

$ make

which successfully compile nq. Unfortunately 

$ make distclean
 rm -f nq
rm -rf .libs _libs
(cd examples; make clean)
make[1]: Entering directory '/home/jo/projects/gap-hap/gap-nq_2.5.4/examples'
rm -f G?.tst  *~
make[1]: Leaving directory '/home/jo/projects/gap-hap/gap-nq_2.5.4/examples'
(cd doc && rm -f *.aux *.bbl *.blg *.brf *.idx *.ilg *.ind *.log *.out *.pnr *.tex *.toc)
(cd doc && rm -f test/nqman.tst test/diffs)
rm -f *.o
rm -f src/*.o
rm -f *.lo
rm -f *.tab.c
test -z "examples/Makefile" || rm -f examples/Makefile
test . = "." || test -z "" || rm -f 
rm -f src/.deps/.dirstamp
rm -f src/.dirstamp
rm -f src/config.h src/stamp-h1
rm -f libtool config.lt
(cd examples; make distclean)
make[1]: Entering directory '/home/jo/projects/gap-hap/gap-nq_2.5.4/examples'
make[1]: *** No rule to make target 'distclean'.  Stop.
make[1]: Leaving directory '/home/jo/projects/gap-hap/gap-nq_2.5.4/examples'
make: *** [Makefile:1253: distclean-local] Error 2

fails. It can't find the distclean target in the Makefile it just deleted. I can work around this by modifying CONFIG_CLEAN_FILES in Makefile.in. Then examples/makefile is however not cleaned anymore.

I do need a working distclean since I am working on a gap-nq debian package.

**Comment by fingolfin** [comment]
Actually, my preference to "fix" this would be to disable "dist" mode and hence distclean, as those are unused and unsupported by this package. As such, `make distclean` will leave things in an undefined / unsupported state. It might result in something useful, or it might produce utter nonsense.
