### ISSUE TITLE
The manual in the tarball differs from the manual generated with makedoc.g

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/nq#11]
If I extract the tarball for nq 2.5.4 and run
echo 'Read("makedoc.g");' | gap -l 'debian/gaproot;/usr/share/gap'
the generated manual.pdf is different from the manual.pdf that was in the tar ball before.

If I modify PackageInfo.g by setting the IsAuthor flag for Max Horn to true and generate the manual.pdf again, the resulting manual is almost identical (only minor font differences) to the one from the tar ball.

This happens on debian testing.
The installed versions are
gap                          4.11.0-4
gap-gapdoc             1.6.3-1
gap-autodoc            2019.09.04-1

The question that arises when packaging this is which documentation is considered correct and therefore will be included in the package.

[manual.tar.pdf](https://github.com/gap-packages/nq/files/5540296/manual.tar.pdf)
[manual.generated.pdf](https://github.com/gap-packages/nq/files/5540299/manual.generated.pdf)
[manual.IsAuthor.pdf](https://github.com/gap-packages/nq/files/5540319/manual.IsAuthor.pdf)

**Comment by narc-Ontakac2** [comment]
This results from 

https://github.com/gap-packages/AutoDoc/commit/07072df15a7b4221e28391417503f3513f769292#diff-dfcc2d48cc39b5329f1eaba46a9e5f152068379eb53d61a57c557f279ecc5893

**Comment by olexandr-konovalov** [comment]
Thanks for finding AutoDoc cause, @narc-Ontakac2 - so, this issue may be closed then?

**Comment by narc-Ontakac2** [comment]
As for packaging I will be regenerating the existing manual unless told otherwise.

As for closing the bug I would suggest we leave it open. Although @fingolfin did the AutoDoc change too, this issue might be an unintentional side effect.  @fingolfin should close it.
