### ISSUE TITLE
Trying to compile nq

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/nq#23]
Foolishly, as a result of discussions on Slack today, I have downloaded packages-master.tar.gz, and also updated my several clones of GAP packages, including Hap (when I should be spending my time developing IdRel).  I cannot load Hap because the nq executable is not available.  So I decide to clone nq.  The README tells me to consult the manual to find installation instructions. (Surely the README could at least instruct the use of ./configure and make and then refer to the manual if these fail.) But anyway, I run gapdev, read makedoc.g, and consult page 23 of the manual.  (Incidentally there is a large variety on this page of '--with' and '-with', so are these equivalent?)  However, folder /nq contains configure.ac but no configure, so I get: 
```Christopher-Wensleys-iMac:nq christopherwensley$ ./configure
-bash: ./configure: No such file or directory'''
Alternatively, using the nq-2.5.5 in packages-master.tar.gz, running ./configure reports to problems, but when I try to make: 
'''Christopher-Wensleys-iMac:nq-2.5.5 christopherwensley$ make
  CC       src/nq-glimt.o
src/glimt.c:17:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
make: *** [src/nq-glimt.o] Error 1'''
and if I try  ./configure --with-gmp="../../extern/gmp", I get:  "configure: WARNING: unrecognized options: --with-gmp"

**Comment by fingolfin** [comment]
Hmm, but what I don't understand: why did you clone nq instead of just building the version in the package distribution tarball?

The manual has only instructions for building release versions. Building a development snapshot assumes an "expert" user who knows to run autogen.sh first, like with all GAP packages that have configure.ac in their repository. One could add instructions for that to the README but this then might end up confusing users of the released version...

**Comment by fingolfin** [comment]
Ah I just noticed that the code snippet at the end of your issue text also contains text discussing nq 2.5.5. but the latest version of nq in the distro is 2.5.8 -- so where is this coming from now?

**Comment by cdwensley** [comment]
You are right - I only decided to clone nq after failing to compile 2.5.5.  So I will get rid of the clone. 
(BTW "nq> git push origin --delete nq"  does not work - what should I be doing?) 
I think the problem is with my gapdev installation because I am having the same problem with float. 
Folder:  gapdev/extern/gmp/  and files: gapdev/extern/install/gmp/include/gmp.h and gapdev/extern/build/gmp/gmp.h  exist, but perhaps gmp.h is expected to be somewhere else?

**Comment by cdwensley** [comment]
Regarding gmp: I have checked that the two occurrences of gmp.h in my gapdev installation are in the same relative location (../extern/...) in my gap4r11 location, so that does not seem to be the problem.

**Comment by cdwensley** [comment]
Now reverting to nq-2.5.4, I find that this does compile and make; can be loaded in gap4r11, but not in gapdev. 
I would be quite happy to have this issue closed and forget all about it if that is what @fingolfin would prefer. 
Here is this afternoon's log: 
```Christopher-Wensleys-iMac:nq-2.5.4 christopherwensley$ make
cnf/install-sh -c -d ./bin/x86_64-apple-darwin17.7.0-default64-kv7
cp nq /Applications/gap/gap4r11/pkg/nq-2.5.4/bin/x86_64-apple-darwin17.7.0-default64-kv7
SUCCESS!

Christopher-Wensleys-iMac:nq-2.5.4 christopherwensley$ ../../../my-dev/dev.sh 
 ┌───────┐   GAP 4.12dev-1285-gdeede6c built on 2022-04-26 15:53:43+0100
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2020.08.11, 
             AutPGrp 1.10.2, Browse 1.8.13, CaratInterface 2.3.3, CRISP 1.4.5, 
             Cryst 4.1.24, CrystCat 1.1.9, CTblLib 1.3.3, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.6, GAPDoc 1.6.5, genss 1.6.6, IO 4.7.2, 
             IRREDSOL 1.4.3, LAGUNA 3.9.3, orb 4.8.4, Polenta 1.3.9, 
             Polycyclic 2.16, PrimGrp 3.4.1, RadiRoot 2.8, recog 1.3.2, 
             ResClasses 4.7.2, SmallGrp 1.4.2, Sophus 1.24, SpinSym 1.5.2, 
             TomLib 1.2.9, TransGrp 3.3, utils 0.72dev
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> SetInfoLevel(InfoPackageLoading,4);
gap> LoadPackage("nq");                 
#I  nq: entering LoadPackage 
#I  nq: PackageAvailabilityInfo for version 2.5.8
#I  Package ``nq'': The executable program is not available
#I  nq: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  nq: PackageAvailabilityInfo for version 2.5.5
#I  Package ``nq'': The executable program is not available
#I  nq: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  nq: PackageAvailabilityInfo for version 2.5.4
#I  Package ``nq'': The executable program is not available
#I  nq: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  nq: PackageAvailabilityInfo: no installed version fits
#I  nq: return from LoadPackage, package is not available
fail
gap> quit;
Christopher-Wensleys-iMac:nq-2.5.4 christopherwensley$ ../../../my-dev/4r11.sh 
 ┌───────┐   GAP 4.11.1 of 2021-03-02
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.7.0-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2020.08.11, 
             AutPGrp 1.10.2, CRISP 1.4.5, Cryst 4.1.23, CrystCat 1.1.9, 
             CTblLib 1.3.1, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.5, 
             GAPDoc 1.6.4, genss 1.6.6, IO 4.7.0, IRREDSOL 1.4.1, 
             LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9, Polycyclic 2.16, 
             PrimGrp 3.4.1, RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, 
             SmallGrp 1.4.2, Sophus 1.24, SpinSym 1.5.2, TomLib 1.2.9, 
             TransGrp 3.0, utils 0.72dev
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> SetInfoLevel(InfoPackageLoading,4);
gap> LoadPackage("nq");
#I  nq: entering LoadPackage 
#I  nq: PackageAvailabilityInfo for version 2.5.8
#I  Package ``nq'': The executable program is not available
#I  nq: PackageAvailabilityInfo: the AvailabilityTest function returned fail
#I  nq: PackageAvailabilityInfo for version 2.5.4
#I  nq: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  nq: PackageAvailabilityInfo: check needed packages
#I      polycyclic (2.11)
#I  nq: PackageAvailabilityInfo: check of needed packages done
#I  nq: PackageAvailabilityInfo: check suggested packages
#I  nq: PackageAvailabilityInfo: check of suggested packages done
#I  nq: PackageAvailabilityInfo: version 2.5.4 is available
#I  nq: start loading needed/suggested/self packages
#I      nq
#I  nq: start reading file 'init.g'
#I  nq: finish reading file 'init.g'
#I  nq: start reading file 'read.g'
#I  nq: finish reading file 'read.g'
Loading nq 2.5.4 (Nilpotent Quotient Algorithm)
  by Werner Nickel
  maintained by Max Horn (max.horn@math.uni-giessen.de)
#I  nq: return from LoadPackage
true

**Comment by cdwensley** [comment]
Please ignore the above - total confusion - will experiment further.

**Comment by cdwensley** [comment]
Have now deleted all my nq files; downloaded nq-2.5.4.tar.gz; opened this into both gap4r11/pkg and gapdev/pkg. 
./compile + make works in 4r11 but fails in dev, with: "fatal error: 'gmp.h' file not found". 
In both 4r11 and dev there are two instances of gmp.h, in the same locations. 
So it appears as if there is something wrong with my gapdev fork. 
Is the sensible thing to do to get rid of this fork and start again? 

```Christopher-Wensleys-iMac:extern christopherwensley$ find . -name gmp.h
./install/gmp/include/gmp.h
./build/gmp/gmp.h

Christopher-Wensleys-iMac:nq-2.5.4 christopherwensley$ make
  CC       src/nq-addgen.o
  CC       src/nq-collect.o
  CC       src/nq-combicol.o
  CC       src/nq-consistency.o
  CC       src/nq-eliminate.o
  CC       src/nq-engel.o
  CC       src/nq-gap.o
  CC       src/nq-glimt.o
src/glimt.c:17:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
make: *** [src/nq-glimt.o] Error 1

**Comment by fingolfin** [comment]
So you are having problems because there is no GMP installed on your computer. GAP deals with it by building its own, but most software will just fail to compile. For a time, NQ tried to "piggy back" on GAP and use GAP's copy of GMP. But this caused other problems I don't want to delve into right now.

Point is: the easiest way to resolve all these troubles with NQ, Float and possibly other packages is to install GMP system wide, and then point them at it. If you use homebrew, that can be done via `brew install gmp`. If you are still on an Intel mac, that's probably all you need to do. If you are on an M1 mac, then homebrew is in another location and you'll have to tell nq (and float, GAP, ...) where it is, by passing `--with-gmp=/opt/homebrew` as an option to the `configure` script.


However, you also can NOT do that, and keep letting GAP build its own GMP, and then try to use that. As I already said, in older versions of nq, it automatically found GMP there, but the current version removed this automagic. So you still need to point the NQ configure script at this copy of GMP, via:

    cd pkg/nq  # or whatever the path is
    ./configure --with-gmp=$GAPROOTDIR/extern/install/gmp

**Comment by fingolfin** [comment]
You also wrote that you tried `git push origin --delete nq` but it "does not work". However, I have no idea what you expected it to do, so I don't know what "did not work". This command would delete a branch named "nq" from the remote git server which is referenced by the local git remote named `origin`. 

If all you want to do is delete your git clone of the `nq` repository, then you can simply `rm -rf nq.git` or use the Finder to move that clone into the trash.

**Comment by fingolfin** [comment]
BTW if you want to use float and build it yourself, then for it to do anything useful, you'll also have to install e.g. `mpfr` and optionally further of its dependencies. Again, this can be done with homebrew (`brew install mpfr`), and again depending on where Homebrew is installed, the float build system will either pick these up automatically, or else may need to be informed about this via `--with-mpfr=PATH/WHERE/MPFR/IS/INSTALL`

**Comment by cdwensley** [comment]
Many thanks for all this advice (which is far more than could reasonably be expected). 
I had not realised that the gmp version supplied with GAP
So Homebrew is now installed, then gmp, and then nq-2.5.8 compiles and the test passes.  Float I do not need. 
(My iMac is 12 years old, runs Mac-OS 10.13.6 and cannot take anything newer, and this is not supported by homebrew, 
so I was expecting problems, but none so far!)

**Comment by cdwensley** [comment]
Meant to say: I had not realised that the gmp version supplied with GAP was inadequate for nq and other packages.
