### ISSUE TITLE
nq doesn't want to build with gap's gmp

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-packages/nq#4]
Nq doesn't want to build with the included version of GMP.  It gives an error message about not finding the header.  I'm building on Mac, but I'm fairly certain this error would persist on any architecture.  If you give --with-gmp=$GAPROOT/extern/install/gmp, then it gives an error message about not finding libgmp.a (the latter could possibly be Mac-specific).

I'm think, but am not certain enough to make a pull request, that the line of configure.ac
		GMP_HOME="$GAPROOT/bin/$GAPARCH/extern/gmp"
should be
		GMP_HOME="$GAPROOT//extern/install/gmp"
at least for recent versions of GAP.  That fixes the first complaint.

I'm not so sure as to what the GMP_LIBS should be when using the built-in GMP.  Perhaps
		GMP_LIBS="-L${GMP_HOME}/lib -lgmp"
would do it??

**Comment by fingolfin** [comment]
This should work fine in nq 2.5.4. If not, please reopen.
