### ISSUE TITLE
Failing tests in GAP master branch

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/nq#5]
Please make a release to include https://github.com/gap-packages/nq/commit/447d148525804daeb3b0cbd6c799972087c101e2 and fix this - otherwise tests fail because of the warning that `SetFeatureObj` is obsolete. See e.g. https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/453439806

**Comment by fingolfin** [comment]
That commit was included in nq 2.5.4 (released in February 2019), and looking at <https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/> it seems that nq tests pass just fine there.
