### ISSUE TITLE
I don't know how to compile nq on a Microsoft computer

### ISSUE THREAD

**Issue by SeidHadiJafari** [gap-packages/nq#7]
In GAP 4.10.2  under windows, when I input the following commands given in 
http://hamilton.nuigalway.ie/Hap/www/SideLinks/About/aboutNonabelian.html,
then it gives error:
```
gap> G:=SmallGroup(32,23);;
gap> K:=CrossedModuleByNormalSubgroup(G,G);;
gap> T2:=Tensor(K,K);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Length' on 1 arguments
The 1st argument is 'fail' which might point to an earlier problem
at /proc/cygdrive/C/gap-4.10.1/lib/methsel2.g:250 called from
Length( result.LowerCentralFactors ) at /proc/cygdrive/C/gap-4.10.1/pkg/nq-2.5.4/gap/nq.gi:273 called from
NqReadOutput( InputTextString( params.output_string )
) at /proc/cygdrive/C/gap-4.10.1/pkg/nq-2.5.4/gap/nq.gi:218 called from
NqCallANU_NQ( rec(
    group := G ) ) at /proc/cygdrive/C/gap-4.10.1/pkg/nq-2.5.4/gap/nq.gi:725 called from
NqEpimorphismNilpotentQuotient( S ) at C:/gap-4.10.1/lib/tensor.gi:100 called from
Tensor( T1, T1 ) at C:/gap-4.10.1/lib/tensor.gi:140 called from
...  at *stdin*:28
type 'quit;' to quit to outer loop 
```
 It seems that GAP fails to retrieve the result of  the calculation with nq.

**Comment by olexandr-konovalov** [comment]
Thanks @SeidHadiJafari. First, I can not reproduce the example: after `LoadPackage("hap");` I still have 
```
gap>  G:=SmallGroup(32,23);;
gap> K:=CrossedModuleByNormalSubgroup(G,G);;
gap> T2:=Tensor(K,K);
Error, Variable: 'Tensor' must have a value
not in any function at *stdin*:7
```
what is strange, since the example looks like the one from the HAP manual. @grahamknockillaree do you have any advice why this might happen?

**Comment by olexandr-konovalov** [comment]
@SeidHadiJafari one more guess: you wrote GAP 4.10.2, but the error message says GAP 4.10.1. Could it be that you have installed one version above another and there is some strange version mismatch now? How did you install and start GAP?

**Comment by grahamknockillaree** [comment]
The following works with HAP1.20, which is available from the GitHub page, or from here http://hamilton.nuigalway.ie/Hap/hap1.20.tar.gz


graham@debian:~$ gap -l '/home/graham;'
 ┌───────┐   GAP 4.10.2 of 19-Jun-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
Syntax warning: Unbound global variable in /usr/share/gap-4.10.2/pkg/grape-4.8\
.2/lib/grape.g:4026
      newdelta:=InducedSubgraph(delta,A,Stabiliser(delta.group,c,OnSets));
                                                  ^
#I  method installed for Matrix matches more than one declaration
 Packages:   AClib 1.3.1, Alnuth 3.1.1, AtlasRep 2.1.0, AutoDoc 2019.05.20, 
             AutPGrp 1.10, Browse 1.8.8, Carat 2.2.3, Congruence 1.2.3, 
             CRISP 1.4.4, Cryst 4.1.19, CrystCat 1.1.9, CTblLib 1.2.2, 
             Digraphs 0.15.2, EDIM 1.3.3, FactInt 1.6.2, FGA 1.4.0, 
             Forms 1.2.5, GAPDoc 1.6.2, genss 1.6.5, GRAPE 4.8.2, 
             groupoids 1.66, HAP 1.20, HAPcryst 0.1.11, IO 4.6.0, 
             IRREDSOL 1.4, LAGUNA 3.9.3, nq 2.5.4, orb 4.8.2, Polenta 1.3.8, 
             Polycyclic 2.14, polymaking 0.8.2, PrimGrp 3.3.2, RadiRoot 2.8, 
             recog 1.3.2, ResClasses 4.7.2, Semigroups 3.1.3, 
             singular 2019.02.22, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5.1, 
             TomLib 1.2.8, TransGrp 2.0.4, utils 0.63, XMod 2.73
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap>  G:=SmallGroup(32,23);;
gap> K:=CrossedModuleByNormalSubgroup(G,G);;
gap> T2:=NonabelianTensorProduct(K,K);
Crossed module with group homomorphism MappingByFunction( Pcp-group with order\
s [ 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 ], Group( [ f1, f2, f3, f4, f5 ] ), 
function ( x )
    return Image( TThomG, x );
end )

All the best,

Graham

**Comment by SeidHadiJafari** [comment]
Dear @alex-konovalov, you are right. I installed the version 4.10.2 again. 
The GAP starts with the following: 

GAP 4.10.2 of 19-Jun-2019
 ?  GAP  ?   https://www.gap-system.org
 ?????????   Architecture: i686-pc-cygwin-default32-kv3
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.1, AtlasRep 2.1.0, AutoDoc 2019.05.20, AutPGrp 1.10, Browse 1.8.8,
             CRISP 1.4.4, Cryst 4.1.19, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, Forms 1.2.5,
             GAPDoc 1.6.2, genss 1.6.5, IO 4.6.0, IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.2, Polenta 1.3.8,
             Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, SmallGrp 1.3,
             Sophus 1.24, SpinSym 1.5.1, TomLib 1.2.8, TransGrp 2.0.4, utils 0.63
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

Then it loads hap by following (I put hap1.20 in pkg file): 

gap> LoadPackage("hap");

After that I see: 

gap> G:=SmallGroup(32,23);;
gap> K:=CrossedModuleByNormalSubgroup(G,G);;
gap> T2:=NonabelianTensorProduct(K,K);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `IsFinite' on 1 arguments at /proc/cygdrive/C/gap-4.10.2/lib/methsel2.g:250 called from
IsFinite( AG ) at /proc/cygdrive/C/gap-4.10.2/pkg/Hap1.20/lib/NonabelianTensor/tensorPair.gi:37 called from
<function "NonabelianTensorProduct">( <arguments> )
 called from read-eval loop at *stdin*:7
type 'quit;' to quit to outer loop
brk>

Beside of this, I have the same problem with the command BaerInvariant(G,c), 
although the commands RelativeSchurMultiplier(G,G) and NonabelianTensorProduct(G,G) work true! 

I think @grahamknockillaree has reproduced it in LINUX.

**Comment by grahamknockillaree** [comment]
Do the following commands work ok for you? Or do you get an error?


gap -l '/home/graham/;' -A
 ┌───────┐   GAP 4.10.2 of 19-Jun-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.2, PrimGrp 3.3.2, SmallGrp 1.3, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("nq");
─────────────────────────────────────────────────────────────────────────────
Loading  AutPGrp 1.10 (Computing the Automorphism Group of a p-Group)
by Bettina Eick (http://www.icm.tu-bs.de/~beick) and
   Eamonn O'Brien (http://www.math.auckland.ac.nz/~obrien).
Homepage: https://gap-packages.github.io/autpgrp/
─────────────────────────────────────────────────────────────────────────────
─────────────────────────────────────────────────────────────────────────────
Loading  Alnuth 3.1.1 (Algebraic number theory and an interface to PARI/GP)
by Björn Assmann,
   Andreas Distler (a.distler@tu-bs.de), and
   Bettina Eick (http://www.icm.tu-bs.de/~beick).
Homepage: https://gap-packages.github.io/alnuth
─────────────────────────────────────────────────────────────────────────────
─────────────────────────────────────────────────────────────────────────────
Loading  Polycyclic 2.14 (Computation with polycyclic groups)
by Bettina Eick (http://www.icm.tu-bs.de/~beick),
   Werner Nickel (http://www.mathematik.tu-darmstadt.de/~nickel/), and
   Max Horn (http://www.quendi.de/math).
Homepage: https://gap-packages.github.io/polycyclic/
─────────────────────────────────────────────────────────────────────────────
Loading nq 2.5.4 (Nilpotent Quotient Algorithm)
  by Werner Nickel
  maintained by Max Horn (max.horn@math.uni-giessen.de)
true
gap> 

Graham


________________________________________

**Comment by SeidHadiJafari** [comment]
I see just the last part, i.e.

gap> LoadPackage("nq"); 
Loading nq 2.5.4 (Nilpotent Quotient Algorithm) by Werner Nickel maintained by Max Horn (max.horn@math.uni-giessen.de) true

**Comment by grahamknockillaree** [comment]
So the nq package is working fine.  I'm puzzled why the IsFinite(AG) does not work on your system.

Could you type

LoadPackage("HAP");

and send me all the details that are printed. Maybe some package is not loading on your maching.



Graham


School of Mathematics, Statistics & Applied Mathematics
National University of Ireland, Galway
http://hamilton.nuigalway.ie
tel: 091 493011

https://global.oup.com/academic/product/an-invitation-to-computational-homotopy-9780198832980
________________________________________

**Comment by SeidHadiJafari** [comment]
```
gap> LoadPackage("hap");
 ───────────────────────────────────────────────────────────────────────────── Loading  Congruence 1.2.3 (Congruence subgroups of SL(2,Integers))
by Ann Dooms (http://homepages.vub.ac.be/~andooms),
   Eric Jespers (http://homepages.vub.ac.be/~efjesper),
   Alexander Konovalov (https://alexk.host.cs.st-andrews.ac.uk), and
   Helena Verrill (http://www.math.lsu.edu/~verrill).
Homepage: https://gap-packages.github.io/congruence
 ───────────────────────────────────────────────────────────────────────────── Loading  EDIM 1.3.3 (Elementary Divisors of Integer Matrices)
by Frank Lübeck (http://www.math.rwth-aachen.de/~Frank.Luebeck).
Homepage: http://www.math.rwth-aachen.de/~Frank.Luebeck/EDIM
 ─────────────────────────────────────────────────────────────────────────────          #I  polymake command not found. Please set POLYMAKE_COMMAND by hand
 ───────────────────────────────────────────────────────────────────────────── Loading  polymaking 0.8.2 (A package for using polymake in GAP)
by Marc Roeder (http://csserver.evansville.edu/~mroeder).
Homepage: https://gap-packages.github.io/polymaking/
 ───────────────────────────────────────────────────────────────────────────── Loading  GRAPE 4.8.2 (GRaph Algorithms using PErmutation groups)
by Leonard H. Soicher (http://www.maths.qmul.ac.uk/~lsoicher/).
Homepage: https://gap-packages.github.io/grape
 ───────────────────────────────────────────────────────────────────────────── Loading  singular 2019.02.22 (A GAP interface to Singular)
by Marco Costantini and
   Willem Adriaan de Graaf (https://www.science.unitn.it/~degraaf/).
Homepage: https://gap-packages.github.io/singular/
 ───────────────────────────────────────────────────────────────────────────── Loading  Digraphs 0.15.2 (Digraphs - Methods for digraphs)
by Jan De Beule (http://homepages.vub.ac.be/~jdbeule/),
   Julius Jonusas (http://www-groups.mcs.st-andrews.ac.uk/~julius/),
   James Mitchell (http://goo.gl/ZtViV6),
   Michael Torpey (http://www-groups.mcs.st-andrews.ac.uk/~mct25/), and
   Wilf Wilson (http://wilf.me).
Homepage: https://gap-packages.github.io/Digraphs
 ─────────────────────────────────────────────────────────────────────────────          #I  method installed for Matrix matches more than one declaration
-----------------------------------------------------------------------------
Loading  Semigroups 3.1.3
by James Mitchell (http://www-groups.mcs.st-andrews.ac.uk/~jamesm/)
with contributions by:
     Stuart Burrell (http://sburrell.nfshost.com),
     Manuel Delgado (http://cmup.fc.up.pt/cmup/mdelgado/),
     James East (http://goo.gl/MuiJu5),
     Attila Egri-Nagy (http://www.egri-nagy.hu),
     Nicholas Ham (https://n-ham.github.io),
     Max Horn (http://www.quendi.de/math),
     Julius Jonusas (http://www-groups.mcs.st-andrews.ac.uk/~julius/),
     Dima V. Pasechnik (http://users.ox.ac.uk/~coml0531/),
     Markus Pfeiffer (https://www.morphism.de/~markusp/),
     Christopher Russell,
     Benjamin Steinberg (http://www.sci.ccny.cuny.edu/~benjamin/),
     Finn Smith,
     Jhevon Smith (http://math.sci.ccny.cuny.edu/people?name=Jhevon_Smith),
     Michael Torpey (http://www-groups.mcs.st-and.ac.uk/~mct25/),
     Murray Whyte,
 and Wilf Wilson (http://wilf.me).
-----------------------------------------------------------------------------
Loading groupoids 1.66 (algorithms for finite groupoids)
by Emma Moore and Chris Wensley (http://pages.bangor.ac.uk/~mas023/)
--------------------------------------------------------------------
#I  HAP warning: Set POLYMAKE_PATH manually if needed.
#I  HAP warning: Set NEATO_PATH manually if needed.
#I  HAP warning: Set DOT_PATH manually if needed.
#I  HAP warning: Set DISPLAY_PATH manually if needed.
#I  HAP warning: Set BROWSER_PATH manually if needed.
#I  HAP warning: Set ASY_PATH manually if needed.
Loading HAP 1.20 ...
----------------------------------------------------------------
This is HAPcryst version 0.1.11
by Marc Roeder
----------------------------------------------------------------
Loading XMod 2.73 (methods for crossed modules and cat1-groups)
by Chris Wensley (http://pages.bangor.ac.uk/~mas023/), with contributions from:
    Murat Alp (muratalp@nigde.edu.tr),
    Alper Odabas (aodabas@ogu.edu.tr),
and Enver Uslu.
-----------------------------------------------------------------------------
true
```

**Comment by grahamknockillaree** [comment]
That output looks fine. So I am still puzzled why IsFinite(AG) does not work on your computer -- I only have a Linux computer and am unable to reproduce your error.

Does the following work on your computer?

gap> F:=FreeGroup(3);;
gap> G:=Image(NqEpimorphismNilpotentQuotient(F,3));;
gap> IsFinite(G);
false


Graham

**Comment by SeidHadiJafari** [comment]
Yes. 
After I loaded "lpres", it works fine.

**Comment by SeidHadiJafari** [comment]
Please take a look at the following error:

gap> G:=SmallGroup(8,3);;
gap> b:=BaerInvariant(G,1);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Length' on 1 arguments
The 1st argument is 'fail' which might point to an earlier problem
 at /proc/cygdrive/C/gap-4.10.2/lib/methsel2.g:250 called from
Length( result.LowerCentralFactors ) at /proc/cygdrive/C/gap-4.10.2/pkg/nq-2.5.4/gap/nq.gi:273 called from
NqReadOutput( InputTextString( params.output_string )
 ) at /proc/cygdrive/C/gap-4.10.2/pkg/nq-2.5.4/gap/nq.gi:218 called from
NqCallANU_NQ( rec(
    group := G ) ) at /proc/cygdrive/C/gap-4.10.2/pkg/nq-2.5.4/gap/nq.gi:725 called from
HAP_NqEpimorphismNilpotentQuotient( U
 ) at /proc/cygdrive/C/gap-4.10.2/pkg/Hap1.20/lib/NonabelianTensor/multNilGrp.gi:37 called from
<function "BaerInvariant">( <arguments> )
 called from read-eval loop at *stdin*:7
type 'quit;' to quit to outer loop
brk>

**Comment by grahamknockillaree** [comment]
On my Linux computer your example works fine. You say that the nq test commands I suggested work fine on your computer. So I don't know what to suggest.

Graham

 ┌───────┐   GAP 4.10.2 of 19-Jun-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
Syntax warning: Unbound global variable in /usr/share/gap-4.10.2/pkg/grape-4.8\
.2/lib/grape.g:4026
      newdelta:=InducedSubgraph(delta,A,Stabiliser(delta.group,c,OnSets));
                                                  ^
#I  method installed for Matrix matches more than one declaration
 Packages:   AClib 1.3.1, Alnuth 3.1.1, AtlasRep 2.1.0, AutoDoc 2019.05.20, 
             AutPGrp 1.10, Browse 1.8.8, Carat 2.2.3, Congruence 1.2.3, 
             CRISP 1.4.4, Cryst 4.1.19, CrystCat 1.1.9, CTblLib 1.2.2, 
             Digraphs 0.15.2, EDIM 1.3.3, FactInt 1.6.2, FGA 1.4.0, 
             Forms 1.2.5, GAPDoc 1.6.2, genss 1.6.5, GRAPE 4.8.2, 
             groupoids 1.66, HAP 1.20, HAPcryst 0.1.11, IO 4.6.0, 
             IRREDSOL 1.4, LAGUNA 3.9.3, nq 2.5.4, orb 4.8.2, Polenta 1.3.8, 
             Polycyclic 2.14, polymaking 0.8.2, PrimGrp 3.3.2, RadiRoot 2.8, 
             recog 1.3.2, ResClasses 4.7.2, Semigroups 3.1.3, 
             singular 2019.02.22, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5.1, 
             TomLib 1.2.8, TransGrp 2.0.4, utils 0.63, XMod 2.73
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> G:=SmallGroup(8,3);;
gap> b:=BaerInvariant(G,1);
[ 2 ]
gap>

**Comment by SeidHadiJafari** [comment]
Many thanks. 
By your idea, should I change my computer windows or any other suggestion? 
Its present windows is 7.

**Comment by grahamknockillaree** [comment]
I suggest you experiment on your computer to find out precisely why your following error happens:

gap> G:=SmallGroup(32,23);;
gap> K:=CrossedModuleByNormalSubgroup(G,G);;
gap> T2:=NonabelianTensorProduct(K,K);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `IsFinite' on 1 arguments at /proc/cygdrive/C/gap-4.10.2/lib/methsel2.g:250 called from
IsFinite( AG ) at /proc/cygdrive/C/gap-4.10.2/pkg/Hap1.20/lib/NonabelianTensor/tensorPair.gi:37 called from
<function "NonabelianTensorProduct">( )
called from read-eval loop at stdin:7


For instance, at the error message type  
AG;
to see what kind of a group AG is. Then try to find out why IsFinite(AG) does not work on your computer for this kind of group. As I don't have a Windows computer I can't investigate this for you.


Graham

**Comment by fingolfin** [comment]
I can't really help with this, as I have no way to test anything on Windows, and no desire to do so. But if others are interested in debugging this, and provide a patch for nq (if needed) or instructions to @SeidHadiJafari , that'd be most welcome.

I am told that these days, using WSL (Windows subsystem for Linux) might be the best way to use GAP on Windows, as it sidesteps all these hassles.

Perhaps @ChrisJefferson has any further insights?

**Comment by ChrisJefferson** [comment]
Firstly, this does work on WSL, and I would recommend using that if possible.

In terms of why it isn't working, libtool is doing something weird I don't understand. It's probably easiest to show the last few lines.

The result of these libtool invocations is a small (26k) nq.exe program, and the "full" nq.exe appearing as .libs/nq.exe. The small nq.exe program, when straced, just looks for ".libs/nq.exe", and when it finds it uses spawnve to run it.

So GAP can find it, we put nq.exe into bin/x86_64-pc-cygwin-default64-kv8/. When run, this nq.exe looks for .libs/nq.exe from it's current location, can't find it, and immediately exits with an error.

I can fix this by:

1) Instead of copying nq.exe, copy .libs/nq.exe (not keeping the .libs) into bin/x86_64-pc-cygwin-default64-kv8/
2) Copy both nq.exe and .libs/nq.exe (keeping the .libs) into bin/x86_64-pc-cygwin-default64-kv8/

I can make a cygwin-specific patch to do one of those (probably the first), if no-one has any obvious idea how to stop libtool being weird.



```
/bin/sh ./libtool  --tag=CC   --mode=link gcc -Wall -Wpointer-arith -Wcast-qual -Wshadow -Wwrite-strings -W -Wc++-compat -Wold-style-definition -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wno-unused-parameter -Wno-long-long -g -O2 -Wl,--stack,16777216 -Wl,--allow-multiple-definition  -o nq.exe src/nq-addgen.o src/nq-collect.o src/nq-combicol.o src/nq-consistency.o src/nq-eliminate.o src/nq-engel.o src/nq-gap.o src/nq-glimt.o src/nq-instances.o src/nq-mem.o src/nq-nq.o src/nq-pc.o src/nq-pcarith.o src/nq-presentation.o src/nq-relations.o src/nq-system.o src/nq-tails.o src/nq-time.o src/nq-trmetab.o src/nq-word.o -lgmp -lz -lreadline
libtool: link: gcc -Wall -Wpointer-arith -Wcast-qual -Wshadow -Wwrite-strings -W -Wc++-compat -Wold-style-definition -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wno-unused-parameter -Wno-long-long -g -O2 -Wl,--stack -Wl,16777216 -Wl,--allow-multiple-definition -o .libs/nq.exe src/nq-addgen.o src/nq-collect.o src/nq-combicol.o src/nq-consistency.o src/nq-eliminate.o src/nq-engel.o src/nq-gap.o src/nq-glimt.o src/nq-instances.o src/nq-mem.o src/nq-nq.o src/nq-pc.o src/nq-pcarith.o src/nq-presentation.o src/nq-relations.o src/nq-system.o src/nq-tails.o src/nq-time.o src/nq-trmetab.o src/nq-word.o  -lgmp -lz -lreadline
/bin/mkdir -p ./bin/x86_64-pc-cygwin-default64-kv8
cp nq /opt/gap-cygwin-fixes/pkg/nq-2.5.4/bin/x86_64-pc-cygwin-default64-kv8
```

**Comment by fingolfin** [comment]
Note that libtool actually isn't needed and PR #12 drops its use; perhaps that helps?

**Comment by ChrisJefferson** [comment]
#12 fixes all the problems, with that I can build nq in the standard way, then load the package and run `tst/nq.tst` successfully.
